name: Deploy to staging

on:
  push:
    branches: [staging]

permissions:
  id-token: write     # <--- REQUIRED for OIDC to work
  contents: read

jobs:
  deploy:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "v1.32.3"
        id: install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.STAGING_GITHUB_ACTION_DEPLOY_ROLE }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: banking-system
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            -f Dockerfile.deploy \
            --build-arg ENVIRONMENT=staging \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update kube config
        run: aws eks --region ap-southeast-1 update-kubeconfig --name eks-banking-system

      - name: Append GitHub Actions IAM role to aws-auth ConfigMap
        env:
          DEPLOY_ROLE_ARN: ${{ secrets.STAGING_GITHUB_ACTION_DEPLOY_ROLE }}
        run: |
          set -e

          kubectl -n kube-system get configmap/aws-auth -o yaml > aws-auth.yaml

          if grep -q "$DEPLOY_ROLE_ARN" aws-auth.yaml; then
            echo "Role already present in aws-auth. Skipping patch."
          else
            if grep -q "mapRoles: |" aws-auth.yaml; then
              sed -i "/mapRoles: |/a\    - rolearn: $DEPLOY_ROLE_ARN\n      username: github-actions\n      groups:\n        - system:masters" aws-auth.yaml
            else
              echo "mapRoles: |" >> aws-auth.yaml
              echo "  - rolearn: $DEPLOY_ROLE_ARN" >> aws-auth.yaml
              echo "    username: github-actions" >> aws-auth.yaml
              echo "    groups:" >> aws-auth.yaml
              echo "      - system:masters" >> aws-auth.yaml
            fi

            kubectl apply -f aws-auth.yaml
            echo "Patched aws-auth with deploy role."
          fi

      - name: Debug - check nodes
        run: kubectl get nodes

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f deployment-manifest/

      - name: Set Image for deployment
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: banking-system
          IMAGE_TAG: ${{ github.sha }}
        run: |
          kubectl set image deployment/banking-system-api-deployment banking-system-api=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Clean up aws-auth.yaml
        run: rm -f aws-auth.yaml